[package]
name = "project-1"
version = "0.1.0"
description = "A key/value store"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
